### ISSUE TITLE
Fisher reports wrong results on some edge cases (overflow?)

### ISSUE THREAD

**Issue by michael-imbeault** [arq5x/bedtools2#343]
I was intersecting lots of bed files with bedtools fisher and noticed some inconsistencies - I had an expected positive result (low p-value) that was negative.

The matrix produced by bedtools is correct:

```
       |  in -b       | not in -b    |
 in -a | 781          | 23171        |
 not in -a | 4963     | 2455001      |
```

However, some of the statistics are not:

p-values for fisher's exact test
left    right   two-tail    ratio
0   1   0   16.673

The expected ratio is correct; however, the right-tail and left-tail p-values are wrong. For comparison, scipy.stats.fisher_exact([[781, 23171], [4963, 2455001]], alternative="greater"), returns a right-tail p-value of 0 (instead of 1 by bedtools) and a left-tail of 0.99999999916069071 (instead of 0 by bedtools).

This behavior is not seen in 99% of the cases, where the results returned are correct.

My guess is that there's an overflow kind of bug somewhere in bedtools fisher calculation of right and left-hand p-values.

As a workaround I'm getting the "not in a, not in b" size of the interval and calculating with scipy.stats.fisher_exact.

**Comment by arq5x** [comment]
Could you post an example so that @brentp and I can give some thought to this?

**Comment by brentp** [comment]
There's a small chance that the left/right lables are flipped, but I think it's showing the correct result, e.g. see the scipy output:

```Python

In [11]: fisher_exact([[781, 23171], [4963, 2455001]], alternative="greater")
Out[11]: (16.672996339673759, 0.0)

In [12]: fisher_exact([[781, 23171], [4963, 2455001]], alternative="less")
Out[12]: (16.672996339673759, 0.99999999916069071)

In [13]: fisher_exact([[781, 23171], [4963, 2455001]], alternative="two-sided")
Out[13]: (16.672996339673759, 0.0)
```

**Comment by brentp** [comment]
the reason it's showing 1 for that right-tail is because the print statement is:
```c++
    printf("%.5g\t%.5g\t%.5g\t%.3f\n", left, right, two, ratio);
```

**Comment by michael-imbeault** [comment]
Here are files to reproduce the issue (txt extensions because of github limitations):

[A.bed.txt](https://github.com/arq5x/bedtools2/files/75754/A.bed.txt)
[B.bed.txt](https://github.com/arq5x/bedtools2/files/75755/B.bed.txt)
[g1k.txt](https://github.com/arq5x/bedtools2/files/75753/g1k.txt)
[A2.bed.txt](https://github.com/arq5x/bedtools2/files/75756/A2.bed.txt)

Do fisher with A2 and B using g1k genome, you get:

# Number of query intervals: 998
# Number of db intervals: 5744
# Number of overlaps: 192
# Number of possible intervals (estimated): 2447563
# phyper(192 - 1, 998, 2447563 - 998, 5744, lower.tail=F)
# Contingency Table Of Counts
#_________________________________________
#           |  in -b       | not in -b    |
#     in -a | 192          | 806          |
# not in -a | 5552         | 2441013      |
#_________________________________________
# p-values for fisher's exact test
left	right	two-tail	ratio
1	4.7905e-297	4.7905e-297	104.734

and scipy gives:

print(scipy.stats.fisher_exact([[192, 806], [5552, 2441013]], alternative="less"))
(104.73379051923256, 0.99999999473132206)
print(scipy.stats.fisher_exact([[192, 806], [5552, 2441013]], alternative="greater"))
(104.73379051923256, 4.790484069498808e-297)
print(scipy.stats.fisher_exact([[192, 806], [5552, 2441013]], alternative="two-sided"))
(104.73379051923256, 4.7904840630505667e-297)

Showing the same right tail ("greater") value of 4.7905e-297 as bedtools.

Now with the problematic bed file, A.bed, bedtools fisher gives:

# Number of query intervals: 23952
# Number of db intervals: 5744
# Number of overlaps: 781
# Number of possible intervals (estimated): 2483916
# phyper(781 - 1, 23952, 2483916 - 23952, 5744, lower.tail=F)
# Contingency Table Of Counts
#_________________________________________
#           |  in -b       | not in -b    |
#     in -a | 781          | 23171        |
# not in -a | 4963         | 2455001      |
#_________________________________________
# p-values for fisher's exact test
left	right	two-tail	ratio
0	1	0	16.673

and scipy:

print(scipy.stats.fisher_exact([[781, 23171], [4963, 2455001]], alternative="less"))
(16.672996339673759, 0.99999999916069071)
print(scipy.stats.fisher_exact([[781, 23171], [4963, 2455001]], alternative="greater"))
(16.672996339673759, 0.0)
print(scipy.stats.fisher_exact([[781, 23171], [4963, 2455001]], alternative="two-sided"))
(16.672996339673759, 0.0)

Notice the discordant p-values for left and right between scipy and bedtools. My guess is an overflow in the fisher calculation.

It's not a display bug, it's a terrible edge case.

Hope its clear now (and happy new year!)

**Comment by jduc** [comment]
I just encountered the exact same issue some days ago and using scipy indeed gave me the correct result. Do you have any news regarding this problem ?

**Comment by brentp** [comment]
@michael-imbeault and @jduc, I just pushed a fix for this to my fisher0 branch in brentp/bedtools2/

if you could try it out, that'd be great.

**Comment by jduc** [comment]
Hello, 

Sorry for the late reply, took me way too long to come back to you - we encountered this fisher issue again today and remembered this issue. 
So I tested your fisher0 branch and it seems to do the trick. This is the results running it with the A.bed.txt and B.bed.txt of the previous post: 

```
# Number of query intervals: 23952
# Number of db intervals: 5685
# Number of overlaps: 781
# Number of possible intervals (estimated): 2488643
# phyper(781 - 1, 23952, 2488643 - 23952, 5685, lower.tail=F)
# Contingency Table Of Counts
#_________________________________________
#           |  in -b       | not in -b    |
#     in -a | 781          | 23171        |
# not in -a | 4904         | 2459787      |
#_________________________________________
# p-values for fisher's exact test
left    right   two-tail        ratio
1       0       0       16.906

```
I also checked that it was giving the same results for the files that were not problematic and it is. So everything seems to be solved in your fisher0 branch. Thanks a lot

**Comment by adjvandijk** [comment]
hi,
I'm using bedtools v2.29.1; seems the above mentioned problem still happens:
Testing several bed files for overlap with bedtools fisher; in most cases, results seem fine, but there is this case:
# Number of query intervals: 4227
# Number of db intervals: 4855
# Number of overlaps: 1183
# Number of possible intervals (estimated): 185666
# phyper(1183 - 1, 4227, 185666 - 4227, 4855, lower.tail=F)
# Contingency Table Of Counts
#_________________________________________
#           |  in -b       | not in -b    |
#     in -a | 1183         | 3044         |
# not in -a | 3672         | 177767       |
#_________________________________________
# p-values for fisher's exact test
left    right   two-tail        ratio
0       1       0       18.814

When I use scipy.stats for this case, I get p-value 0:
scipy.stats.fisher_exact([[1183, 3044], [3672, 177767]], alternative="greater")
(18.814321773752575, 0.0)
