### ISSUE TITLE
IntersectBed error with gff.gz file as input

### ISSUE THREAD

**Issue by sdjebali** [arq5x/bedtools2#353]
Dear all,

I am using the latest version of intersectBed (source code directly taken from github yesterday and compiled, DETECTED_VERSION = v2.25.0-51-g4e1b658).

I use it with two gff.gz files as input, like this:
bedtools intersect -wao -a contiguousAlignments.gff.gz -b annotatedExons.gff.gz | gzip > contiguousAlignments_intersected2.txt.gz 2> intersect.err

The first file looks like this:
chr1    ChimPipe        alBlock 69181   69281   1       +       .       ReadName: "ENST00000335137.3-104/2";

and the second file like this:
chr1    HAVANA  exon    11869   12227   .       +       .       gene_id "ENSG00000223972.4"; gene_name "DDX11L1"; gene_type "pseudogene"; transcript_id "ENST00000456328.2";

I think my two gff.gz files are well formatted, with 9 fields separated by tabs, however I get an error message after a certain time of computation:
Error: line number 18921599 of file contiguousAlignments.gff.gz has 6 fields, but 9 were expected.
and a truncated output

I have placed the two input files and the output file here:
http://genome.crg.es/~sdjebali/BugReport2.tar.gz

Let me know if you need more information from my side?

Best regards,
Sarah

**Comment by arq5x** [comment]
Hi Sarah,

Very sorry for the delay, I have been busy with pressing deadlines. This issue is resolved by this commit: https://github.com/arq5x/bedtools2/commit/9b734e634e3f42784099d2cd77177a90fa4e5f37. If you can retest with a fresh clone from this repository, I think you will be in business.

**Comment by sdjebali** [comment]
Thank you very much
Will try today
Cheers


On Thu, Feb 4, 2016 at 12:17 AM, Aaron Quinlan <notifications@github.com>
wrote:

> Hi Sarah,
>
> Very sorry for the delay, I have been busy with pressing deadlines. This
> issue is resolved by this commit: 9b734e6
> <https://github.com/arq5x/bedtools2/commit/9b734e634e3f42784099d2cd77177a90fa4e5f37>.
> If you can retest with a fresh clone from this repository, I think you will
> be in business.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/bedtools2/issues/353#issuecomment-179524579>.
>



-- 
***********************************************************
Sarah Djebali Quelen - PhD
INRA GenPhySE, ch. de Borderouge
31326 Castanet-Tolosan, France
Tel. +33 5 61 28 51 22
sarah.djebali-quelen at toulouse dot inra dot fr

**Comment by sdjebali** [comment]
Hello,

I tried with the latest source (DETECTED_VERSION = v2.25.0-68-g447c995-dirty) and I still get the same error message:
Error: line number 18921599 of file /no_backup/rg/sdjebali/Chimeras/ChimPipe/benchmark/ChimPipe-0.9.3/Simulated_Chimeras_Normal/101/ChimeraDetectionPhase/ChimPE/contiguousAlignments.gff.gz has 6 fields, but 9 were expected.

Thanks,
Sarah
