### ISSUE TITLE
GroupBy not working as expected in 2.26.0

### ISSUE THREAD

**Issue by duartemolha** [arq5x/bedtools2#453]
Hi Guys 

I have installed bedtools 2.26.0 and groupby is not working as expected... I tried the same exact command on an earlier version and it did the right thing

consider a file test.txt with the following tab-delimited data:
5S_rRNA 106
5S_rRNA 111
5S_rRNA 115
5S_rRNA 116
5S_rRNA 118
5S_rRNA 118
5S_rRNA 274
5S_rRNA 76
5S_rRNA,RNA5SP423       1338
7SK     111
7SK     188
7SK     194
7SK     2774
7SK     290
7SK     300
7SK     321
7SK     356
7SK     377
7SK     382
7SK     74

`bedtools-2.23.0/bin/groupBy -g 1 -c 2 -o sum -i test.txt
`
results in the expected output:

5S_rRNA 1034
5S_rRNA,RNA5SP423       1338
7SK     5367

`bedtools-2.26.0/bin/groupBy -g 1 -c 2 -o sum -i test.txt
`
if done on the lastest version I get:
7739
which is the sum of all the 2nd column, but not grouped by the 1st column as I requested

Is this a known bug?

**Comment by duartemolha** [comment]
anyone?

**Comment by arq5x** [comment]
Sorry, was travelling. This is fixed in master and will be in the next release (a few weeks out).

**Comment by duartemolha** [comment]
Apologies ... should have checked before... there had been other people reporting on this.

Many thanks

**Comment by duartemolha** [comment]
Sorry to reopen this ... but I downloaded te latest from the repo and this is this not fixed ... when you say it is fixed on master, what do you mean? in this not where you keep the master repo?!

**Comment by arq5x** [comment]
I suspect your problem is that you are running the "groupby" shell script and the script you are running is still pointing to the bedtools executable for 2.26.0 (not what you compiled from github). Try running:

    bin/bedtools groupby -g 1 -c 2 -o sum -i test.txt

From the directory in which you cloned and compiled bedtools from Github.  I just tried this and it works as expected. For this reason, I would recommend trying to transition your usage of bedtools to explicitly calling the bedtools executable with a subcommand.

Please reopen if this still does not work for you.
